version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosstem: "nuget"
    directory: "/code/
    schedule: 
      interval: "weekly"
      
